spring:
  datasource:
    url: jdbc:h2:mem:peoplepulse;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use "create-drop" during development for automatic schema creation and drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true  # Show SQL queries in logs for debugging
    properties:
      hibernate:
        format_sql: true  # Format SQL for readability
        use_sql_comments: true  # Add SQL comments for easier debugging

  # Logging Configuration
  logging:
    level:
      io:
        peoplepulse: DEBUG  # Set the log level for your application
      org:
        springframework: INFO
        hibernate: DEBUG

  # Swagger Configuration (SpringDoc OpenAPI)
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  sql:
    init:
      mode: always  # Automatically run the schema from schema.sql if it exists

# H2 Console for easy access during development
h2:
  console:
    enabled: true
    path: /h2-console  # Accessible via http://localhost:8080/h2-console

# Enable resilience4j configuration if needed for retries, timeouts, etc.
resilience4j:
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

# External api urls
urlmappings:
  data-set-provider:
    base-url: https://dummyjson.com
    get-users: /users
